// PLFrontendActiveX.idl : IDL source for PLFrontendActiveX
//

// This file will be processed by the MIDL tool to
// produce the type library (PLFrontendActiveX.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(607EF132-35D2-4832-8653-C2D8FDC3022E),
	dual,
	nonextensible,
	helpstring("IPixelLightCtrl Interface"),
	pointer_default(unique)
]
interface IPixelLightCtrl : IDispatch{
};

[
	uuid(F4D3DAA8-A984-4929-A61A-4F19F33A9D9E),
	version(1.0),
	helpstring("PLFrontendActiveX 1.0 Type Library")
]
library PLFrontendActiveXLib
{
	importlib("stdole2.tlb");
	[
		uuid(AF181E78-519B-4A35-99CE-2348A32E28EA),
		control,
		helpstring("PixelLightCtrl Class")
	]
	coclass PixelLightCtrl
	{
		[default] interface IPixelLightCtrl;
	};
};
