#ifndef PLEDITORPLUGINBASE_GLOBAL_H
#define PLEDITORPLUGINBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLEDITORPLUGINBASE_LIBRARY)
#  define PLEDITORPLUGINBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLEDITORPLUGINBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLEDITORPLUGINBASE_GLOBAL_H
